/********************************************************************************
** Form generated from reading UI file 'rhythm_game.ui'
**
** Created by: Qt User Interface Compiler version 5.3.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_RHYTHM_GAME_H
#define UI_RHYTHM_GAME_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QGraphicsView>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_Rhythm_GameClass
{
public:
    QWidget *centralWidget;
    QStackedWidget *stacked_widget;
    QWidget *intro_video_widget;
    QGraphicsView *intro_video;
    QWidget *main_widget;
    QPushButton *start_button;
    QPushButton *quit_button;
    QLabel *camera;
    QWidget *stage_1_widget;
    QPushButton *stage_4;
    QLabel *camera_6;
    QWidget *stage_2_widget;
    QPushButton *stage_5;
    QPushButton *stage_6;
    QPushButton *left_button_2;
    QPushButton *right_button_2;
    QLabel *camera_7;
    QWidget *stage_3_widget;
    QPushButton *left_button;
    QPushButton *right_button;
    QPushButton *stage_1;
    QPushButton *stage_2;
    QPushButton *stage_3;
    QLabel *camera_2;
    QWidget *video_widget;
    QGraphicsView *video;
    QPushButton *next_button;
    QWidget *play_1_widget;
    QPushButton *apple;
    QPushButton *bus;
    QPushButton *cat;
    QPushButton *duck;
    QLabel *camera_3;
    QWidget *play_2_widget;
    QLabel *camera_8;
    QPushButton *elephant;
    QPushButton *frog;
    QPushButton *gorilla;
    QPushButton *horse;
    QWidget *result_great_widget;
    QLabel *great;
    QPushButton *return_main;
    QPushButton *quit_button_2;
    QLabel *camera_4;
    QWidget *result_fail_widget;
    QLabel *camera_5;
    QLabel *fail;
    QPushButton *quit_button_3;
    QPushButton *return_main_2;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *Rhythm_GameClass)
    {
        if (Rhythm_GameClass->objectName().isEmpty())
            Rhythm_GameClass->setObjectName(QStringLiteral("Rhythm_GameClass"));
        Rhythm_GameClass->resize(1300, 750);
        centralWidget = new QWidget(Rhythm_GameClass);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        stacked_widget = new QStackedWidget(centralWidget);
        stacked_widget->setObjectName(QStringLiteral("stacked_widget"));
        stacked_widget->setGeometry(QRect(0, 12, 1280, 720));
        intro_video_widget = new QWidget();
        intro_video_widget->setObjectName(QStringLiteral("intro_video_widget"));
        intro_video = new QGraphicsView(intro_video_widget);
        intro_video->setObjectName(QStringLiteral("intro_video"));
        intro_video->setGeometry(QRect(0, 0, 1280, 720));
        stacked_widget->addWidget(intro_video_widget);
        main_widget = new QWidget();
        main_widget->setObjectName(QStringLiteral("main_widget"));
        start_button = new QPushButton(main_widget);
        start_button->setObjectName(QStringLiteral("start_button"));
        start_button->setGeometry(QRect(50, 600, 400, 80));
        start_button->setStyleSheet(QStringLiteral("background-image: url(C:/image/startButtonBasic.png);"));
        quit_button = new QPushButton(main_widget);
        quit_button->setObjectName(QStringLiteral("quit_button"));
        quit_button->setGeometry(QRect(850, 600, 400, 80));
        quit_button->setStyleSheet(QStringLiteral("background-image: url(C:/image/quitButtonBasic.png);"));
        camera = new QLabel(main_widget);
        camera->setObjectName(QStringLiteral("camera"));
        camera->setGeometry(QRect(0, 12, 1280, 720));
        stacked_widget->addWidget(main_widget);
        camera->raise();
        start_button->raise();
        quit_button->raise();
        stage_1_widget = new QWidget();
        stage_1_widget->setObjectName(QStringLiteral("stage_1_widget"));
        stage_4 = new QPushButton(stage_1_widget);
        stage_4->setObjectName(QStringLiteral("stage_4"));
        stage_4->setGeometry(QRect(520, 350, 300, 250));
        stage_4->setStyleSheet(QStringLiteral("background-image: url(C:/image/stage1.png);"));
        camera_6 = new QLabel(stage_1_widget);
        camera_6->setObjectName(QStringLiteral("camera_6"));
        camera_6->setGeometry(QRect(0, 12, 1280, 720));
        stacked_widget->addWidget(stage_1_widget);
        camera_6->raise();
        stage_4->raise();
        stage_2_widget = new QWidget();
        stage_2_widget->setObjectName(QStringLiteral("stage_2_widget"));
        stage_5 = new QPushButton(stage_2_widget);
        stage_5->setObjectName(QStringLiteral("stage_5"));
        stage_5->setGeometry(QRect(520, 350, 300, 250));
        stage_5->setStyleSheet(QStringLiteral("background-image: url(C:/image/stage1.png);"));
        stage_6 = new QPushButton(stage_2_widget);
        stage_6->setObjectName(QStringLiteral("stage_6"));
        stage_6->setGeometry(QRect(520, 350, 300, 250));
        stage_6->setStyleSheet(QStringLiteral("background-image: url(C:/image/stage2.png);"));
        left_button_2 = new QPushButton(stage_2_widget);
        left_button_2->setObjectName(QStringLiteral("left_button_2"));
        left_button_2->setGeometry(QRect(50, 280, 191, 400));
        QPalette palette;
        QBrush brush(QColor(0, 0, 0, 0));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Active, QPalette::Button, brush);
        palette.setBrush(QPalette::Active, QPalette::Light, brush);
        palette.setBrush(QPalette::Active, QPalette::Midlight, brush);
        palette.setBrush(QPalette::Active, QPalette::Dark, brush);
        palette.setBrush(QPalette::Active, QPalette::Mid, brush);
        palette.setBrush(QPalette::Active, QPalette::Text, brush);
        palette.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Active, QPalette::Base, brush);
        palette.setBrush(QPalette::Active, QPalette::Window, brush);
        palette.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Active, QPalette::Highlight, brush);
        palette.setBrush(QPalette::Active, QPalette::HighlightedText, brush);
        palette.setBrush(QPalette::Active, QPalette::Link, brush);
        palette.setBrush(QPalette::Active, QPalette::LinkVisited, brush);
        palette.setBrush(QPalette::Active, QPalette::AlternateBase, brush);
        QBrush brush1(QColor(0, 0, 0, 5));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::NoRole, brush1);
        palette.setBrush(QPalette::Active, QPalette::ToolTipBase, brush);
        palette.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Light, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Midlight, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Dark, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Mid, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Highlight, brush);
        palette.setBrush(QPalette::Inactive, QPalette::HighlightedText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Link, brush);
        palette.setBrush(QPalette::Inactive, QPalette::LinkVisited, brush);
        palette.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush);
        palette.setBrush(QPalette::Inactive, QPalette::NoRole, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette.setBrush(QPalette::Disabled, QPalette::Light, brush);
        palette.setBrush(QPalette::Disabled, QPalette::Midlight, brush);
        palette.setBrush(QPalette::Disabled, QPalette::Dark, brush);
        palette.setBrush(QPalette::Disabled, QPalette::Mid, brush);
        palette.setBrush(QPalette::Disabled, QPalette::Text, brush);
        palette.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush);
        palette.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        QBrush brush2(QColor(0, 120, 215, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Disabled, QPalette::Highlight, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::HighlightedText, brush);
        palette.setBrush(QPalette::Disabled, QPalette::Link, brush);
        palette.setBrush(QPalette::Disabled, QPalette::LinkVisited, brush);
        palette.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush);
        palette.setBrush(QPalette::Disabled, QPalette::NoRole, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        left_button_2->setPalette(palette);
        left_button_2->setStyleSheet(QStringLiteral("background-image: url(C:/image/leftButtonBasic.png);"));
        right_button_2 = new QPushButton(stage_2_widget);
        right_button_2->setObjectName(QStringLiteral("right_button_2"));
        right_button_2->setGeometry(QRect(1080, 280, 201, 400));
        QPalette palette1;
        palette1.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Active, QPalette::Button, brush);
        palette1.setBrush(QPalette::Active, QPalette::Light, brush);
        palette1.setBrush(QPalette::Active, QPalette::Midlight, brush);
        palette1.setBrush(QPalette::Active, QPalette::Dark, brush);
        palette1.setBrush(QPalette::Active, QPalette::Mid, brush);
        palette1.setBrush(QPalette::Active, QPalette::Text, brush);
        palette1.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette1.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Active, QPalette::Base, brush);
        palette1.setBrush(QPalette::Active, QPalette::Window, brush);
        palette1.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette1.setBrush(QPalette::Active, QPalette::Highlight, brush);
        palette1.setBrush(QPalette::Active, QPalette::HighlightedText, brush);
        palette1.setBrush(QPalette::Active, QPalette::Link, brush);
        palette1.setBrush(QPalette::Active, QPalette::LinkVisited, brush);
        palette1.setBrush(QPalette::Active, QPalette::AlternateBase, brush);
        palette1.setBrush(QPalette::Active, QPalette::NoRole, brush);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipBase, brush);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Light, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Midlight, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Dark, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Mid, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Highlight, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::HighlightedText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Link, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::LinkVisited, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::NoRole, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::Light, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::Midlight, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::Dark, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::Mid, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::Text, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::Window, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::Highlight, brush2);
        palette1.setBrush(QPalette::Disabled, QPalette::HighlightedText, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::Link, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::LinkVisited, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::NoRole, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        right_button_2->setPalette(palette1);
        right_button_2->setStyleSheet(QStringLiteral("background-image: url(C:/image/rightButtonBasic.png);"));
        camera_7 = new QLabel(stage_2_widget);
        camera_7->setObjectName(QStringLiteral("camera_7"));
        camera_7->setGeometry(QRect(0, 12, 1280, 720));
        stacked_widget->addWidget(stage_2_widget);
        camera_7->raise();
        stage_6->raise();
        left_button_2->raise();
        right_button_2->raise();
        stage_5->raise();
        stage_3_widget = new QWidget();
        stage_3_widget->setObjectName(QStringLiteral("stage_3_widget"));
        left_button = new QPushButton(stage_3_widget);
        left_button->setObjectName(QStringLiteral("left_button"));
        left_button->setGeometry(QRect(50, 280, 191, 400));
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Active, QPalette::Button, brush);
        palette2.setBrush(QPalette::Active, QPalette::Light, brush);
        palette2.setBrush(QPalette::Active, QPalette::Midlight, brush);
        palette2.setBrush(QPalette::Active, QPalette::Dark, brush);
        palette2.setBrush(QPalette::Active, QPalette::Mid, brush);
        palette2.setBrush(QPalette::Active, QPalette::Text, brush);
        palette2.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette2.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette2.setBrush(QPalette::Active, QPalette::Base, brush);
        palette2.setBrush(QPalette::Active, QPalette::Window, brush);
        palette2.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette2.setBrush(QPalette::Active, QPalette::Highlight, brush);
        palette2.setBrush(QPalette::Active, QPalette::HighlightedText, brush);
        palette2.setBrush(QPalette::Active, QPalette::Link, brush);
        palette2.setBrush(QPalette::Active, QPalette::LinkVisited, brush);
        palette2.setBrush(QPalette::Active, QPalette::AlternateBase, brush);
        palette2.setBrush(QPalette::Active, QPalette::NoRole, brush1);
        palette2.setBrush(QPalette::Active, QPalette::ToolTipBase, brush);
        palette2.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Light, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Midlight, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Dark, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Mid, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Highlight, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::HighlightedText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Link, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::LinkVisited, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::NoRole, brush1);
        palette2.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::Light, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::Midlight, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::Dark, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::Mid, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::Text, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::ButtonText, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::Window, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::Highlight, brush2);
        palette2.setBrush(QPalette::Disabled, QPalette::HighlightedText, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::Link, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::LinkVisited, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::NoRole, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        left_button->setPalette(palette2);
        left_button->setStyleSheet(QStringLiteral("background-image: url(C:/image/leftButtonBasic.png);"));
        right_button = new QPushButton(stage_3_widget);
        right_button->setObjectName(QStringLiteral("right_button"));
        right_button->setGeometry(QRect(1090, 280, 201, 400));
        QPalette palette3;
        palette3.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette3.setBrush(QPalette::Active, QPalette::Button, brush);
        palette3.setBrush(QPalette::Active, QPalette::Light, brush);
        palette3.setBrush(QPalette::Active, QPalette::Midlight, brush);
        palette3.setBrush(QPalette::Active, QPalette::Dark, brush);
        palette3.setBrush(QPalette::Active, QPalette::Mid, brush);
        palette3.setBrush(QPalette::Active, QPalette::Text, brush);
        palette3.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette3.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette3.setBrush(QPalette::Active, QPalette::Base, brush);
        palette3.setBrush(QPalette::Active, QPalette::Window, brush);
        palette3.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette3.setBrush(QPalette::Active, QPalette::Highlight, brush);
        palette3.setBrush(QPalette::Active, QPalette::HighlightedText, brush);
        palette3.setBrush(QPalette::Active, QPalette::Link, brush);
        palette3.setBrush(QPalette::Active, QPalette::LinkVisited, brush);
        palette3.setBrush(QPalette::Active, QPalette::AlternateBase, brush);
        palette3.setBrush(QPalette::Active, QPalette::NoRole, brush);
        palette3.setBrush(QPalette::Active, QPalette::ToolTipBase, brush);
        palette3.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Light, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Midlight, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Dark, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Mid, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Highlight, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::HighlightedText, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Link, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::LinkVisited, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::NoRole, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::Light, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::Midlight, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::Dark, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::Mid, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::Text, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::ButtonText, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::Window, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::Highlight, brush2);
        palette3.setBrush(QPalette::Disabled, QPalette::HighlightedText, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::Link, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::LinkVisited, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::NoRole, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        right_button->setPalette(palette3);
        right_button->setStyleSheet(QStringLiteral("background-image: url(C:/image/rightButtonBasic.png);"));
        stage_1 = new QPushButton(stage_3_widget);
        stage_1->setObjectName(QStringLiteral("stage_1"));
        stage_1->setGeometry(QRect(520, 350, 300, 250));
        stage_1->setStyleSheet(QStringLiteral("background-image: url(C:/image/stage1.png);"));
        stage_2 = new QPushButton(stage_3_widget);
        stage_2->setObjectName(QStringLiteral("stage_2"));
        stage_2->setGeometry(QRect(520, 350, 300, 250));
        stage_2->setStyleSheet(QStringLiteral("background-image: url(C:/image/stage2.png);"));
        stage_3 = new QPushButton(stage_3_widget);
        stage_3->setObjectName(QStringLiteral("stage_3"));
        stage_3->setGeometry(QRect(520, 350, 300, 250));
        stage_3->setStyleSheet(QStringLiteral("background-image: url(C:/image/stage3.png);"));
        camera_2 = new QLabel(stage_3_widget);
        camera_2->setObjectName(QStringLiteral("camera_2"));
        camera_2->setGeometry(QRect(0, 12, 1280, 720));
        stacked_widget->addWidget(stage_3_widget);
        camera_2->raise();
        left_button->raise();
        right_button->raise();
        stage_2->raise();
        stage_3->raise();
        stage_1->raise();
        video_widget = new QWidget();
        video_widget->setObjectName(QStringLiteral("video_widget"));
        video = new QGraphicsView(video_widget);
        video->setObjectName(QStringLiteral("video"));
        video->setGeometry(QRect(0, 12, 1280, 720));
        next_button = new QPushButton(video_widget);
        next_button->setObjectName(QStringLiteral("next_button"));
        next_button->setGeometry(QRect(1170, 620, 60, 60));
        QPalette palette4;
        palette4.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette4.setBrush(QPalette::Active, QPalette::Button, brush);
        palette4.setBrush(QPalette::Active, QPalette::Light, brush);
        palette4.setBrush(QPalette::Active, QPalette::Midlight, brush);
        palette4.setBrush(QPalette::Active, QPalette::Dark, brush);
        palette4.setBrush(QPalette::Active, QPalette::Mid, brush);
        palette4.setBrush(QPalette::Active, QPalette::Text, brush);
        palette4.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette4.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette4.setBrush(QPalette::Active, QPalette::Base, brush);
        palette4.setBrush(QPalette::Active, QPalette::Window, brush);
        palette4.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette4.setBrush(QPalette::Active, QPalette::Highlight, brush);
        palette4.setBrush(QPalette::Active, QPalette::HighlightedText, brush);
        palette4.setBrush(QPalette::Active, QPalette::Link, brush);
        palette4.setBrush(QPalette::Active, QPalette::LinkVisited, brush);
        palette4.setBrush(QPalette::Active, QPalette::AlternateBase, brush);
        palette4.setBrush(QPalette::Active, QPalette::NoRole, brush);
        palette4.setBrush(QPalette::Active, QPalette::ToolTipBase, brush);
        palette4.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Light, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Midlight, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Dark, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Mid, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Highlight, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::HighlightedText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Link, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::LinkVisited, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::NoRole, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::Light, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::Midlight, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::Dark, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::Mid, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::Text, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::ButtonText, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::Window, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::Highlight, brush2);
        palette4.setBrush(QPalette::Disabled, QPalette::HighlightedText, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::Link, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::LinkVisited, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::NoRole, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        next_button->setPalette(palette4);
        next_button->setStyleSheet(QStringLiteral("background-image: url(C:/image/next.png);"));
        stacked_widget->addWidget(video_widget);
        play_1_widget = new QWidget();
        play_1_widget->setObjectName(QStringLiteral("play_1_widget"));
        apple = new QPushButton(play_1_widget);
        apple->setObjectName(QStringLiteral("apple"));
        apple->setGeometry(QRect(1020, 420, 200, 200));
        apple->setStyleSheet(QStringLiteral("background-image : url(C:/image/apple.png)"));
        bus = new QPushButton(play_1_widget);
        bus->setObjectName(QStringLiteral("bus"));
        bus->setGeometry(QRect(330, 120, 200, 200));
        bus->setStyleSheet(QStringLiteral("background-image : url(C:/image/bus.png)"));
        cat = new QPushButton(play_1_widget);
        cat->setObjectName(QStringLiteral("cat"));
        cat->setGeometry(QRect(730, 120, 200, 200));
        cat->setStyleSheet(QStringLiteral("background-image : url(C:/image/cat.png)"));
        duck = new QPushButton(play_1_widget);
        duck->setObjectName(QStringLiteral("duck"));
        duck->setGeometry(QRect(50, 420, 200, 200));
        duck->setStyleSheet(QStringLiteral("background-image : url(C:/image/duck.png)"));
        camera_3 = new QLabel(play_1_widget);
        camera_3->setObjectName(QStringLiteral("camera_3"));
        camera_3->setGeometry(QRect(0, 12, 1280, 720));
        stacked_widget->addWidget(play_1_widget);
        camera_3->raise();
        apple->raise();
        bus->raise();
        cat->raise();
        duck->raise();
        play_2_widget = new QWidget();
        play_2_widget->setObjectName(QStringLiteral("play_2_widget"));
        camera_8 = new QLabel(play_2_widget);
        camera_8->setObjectName(QStringLiteral("camera_8"));
        camera_8->setGeometry(QRect(0, 12, 1280, 720));
        elephant = new QPushButton(play_2_widget);
        elephant->setObjectName(QStringLiteral("elephant"));
        elephant->setGeometry(QRect(120, 440, 200, 200));
        elephant->setStyleSheet(QStringLiteral("background-image : url(C:/image/elephant.png)"));
        frog = new QPushButton(play_2_widget);
        frog->setObjectName(QStringLiteral("frog"));
        frog->setGeometry(QRect(790, 110, 200, 200));
        frog->setStyleSheet(QStringLiteral("background-image : url(C:/image/frog.png)"));
        gorilla = new QPushButton(play_2_widget);
        gorilla->setObjectName(QStringLiteral("gorilla"));
        gorilla->setGeometry(QRect(340, 110, 200, 200));
        gorilla->setStyleSheet(QStringLiteral("background-image : url(C:/image/gorilla.png)"));
        horse = new QPushButton(play_2_widget);
        horse->setObjectName(QStringLiteral("horse"));
        horse->setGeometry(QRect(1050, 440, 200, 200));
        horse->setStyleSheet(QStringLiteral("background-image : url(C:/image/horse.png)"));
        stacked_widget->addWidget(play_2_widget);
        result_great_widget = new QWidget();
        result_great_widget->setObjectName(QStringLiteral("result_great_widget"));
        great = new QLabel(result_great_widget);
        great->setObjectName(QStringLiteral("great"));
        great->setGeometry(QRect(140, 60, 500, 600));
        great->setStyleSheet(QStringLiteral("background-image : url(C:/image/great.png)"));
        return_main = new QPushButton(result_great_widget);
        return_main->setObjectName(QStringLiteral("return_main"));
        return_main->setGeometry(QRect(720, 260, 450, 100));
        return_main->setStyleSheet(QStringLiteral("background-image : url(C:/image/mainButtonBasic.png)"));
        quit_button_2 = new QPushButton(result_great_widget);
        quit_button_2->setObjectName(QStringLiteral("quit_button_2"));
        quit_button_2->setGeometry(QRect(750, 430, 400, 80));
        quit_button_2->setStyleSheet(QStringLiteral("background-image : url(C:/image/quitButtonBasic.png)"));
        camera_4 = new QLabel(result_great_widget);
        camera_4->setObjectName(QStringLiteral("camera_4"));
        camera_4->setGeometry(QRect(0, 12, 1280, 720));
        stacked_widget->addWidget(result_great_widget);
        camera_4->raise();
        return_main->raise();
        quit_button_2->raise();
        great->raise();
        result_fail_widget = new QWidget();
        result_fail_widget->setObjectName(QStringLiteral("result_fail_widget"));
        camera_5 = new QLabel(result_fail_widget);
        camera_5->setObjectName(QStringLiteral("camera_5"));
        camera_5->setGeometry(QRect(0, 12, 1280, 720));
        fail = new QLabel(result_fail_widget);
        fail->setObjectName(QStringLiteral("fail"));
        fail->setGeometry(QRect(140, 60, 500, 600));
        fail->setStyleSheet(QStringLiteral("background-image : url(C:/image/fail.png)"));
        quit_button_3 = new QPushButton(result_fail_widget);
        quit_button_3->setObjectName(QStringLiteral("quit_button_3"));
        quit_button_3->setGeometry(QRect(750, 430, 400, 80));
        quit_button_3->setStyleSheet(QStringLiteral("background-image : url(C:/image/quitButtonBasic.png)"));
        return_main_2 = new QPushButton(result_fail_widget);
        return_main_2->setObjectName(QStringLiteral("return_main_2"));
        return_main_2->setGeometry(QRect(720, 260, 450, 100));
        return_main_2->setStyleSheet(QStringLiteral("background-image : url(C:/image/mainButtonBasic.png)"));
        stacked_widget->addWidget(result_fail_widget);
        Rhythm_GameClass->setCentralWidget(centralWidget);
        mainToolBar = new QToolBar(Rhythm_GameClass);
        mainToolBar->setObjectName(QStringLiteral("mainToolBar"));
        Rhythm_GameClass->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(Rhythm_GameClass);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        Rhythm_GameClass->setStatusBar(statusBar);

        retranslateUi(Rhythm_GameClass);
        QObject::connect(start_button, SIGNAL(clicked()), Rhythm_GameClass, SLOT(enter_stage()));
        QObject::connect(quit_button, SIGNAL(clicked()), Rhythm_GameClass, SLOT(exit_game()));
        QObject::connect(right_button, SIGNAL(clicked()), Rhythm_GameClass, SLOT(change_next_stage()));
        QObject::connect(left_button, SIGNAL(clicked()), Rhythm_GameClass, SLOT(change_before_stage()));
        QObject::connect(stage_1, SIGNAL(clicked()), Rhythm_GameClass, SLOT(play_video()));
        QObject::connect(stage_2, SIGNAL(clicked()), Rhythm_GameClass, SLOT(play_video()));
        QObject::connect(stage_3, SIGNAL(clicked()), Rhythm_GameClass, SLOT(play_video()));
        QObject::connect(return_main, SIGNAL(clicked()), Rhythm_GameClass, SLOT(enter_stage()));
        QObject::connect(quit_button_2, SIGNAL(clicked()), Rhythm_GameClass, SLOT(exit_game()));
        QObject::connect(next_button, SIGNAL(clicked()), Rhythm_GameClass, SLOT(play_game()));
        QObject::connect(bus, SIGNAL(clicked()), Rhythm_GameClass, SLOT(check_answer()));
        QObject::connect(cat, SIGNAL(clicked()), Rhythm_GameClass, SLOT(check_answer()));
        QObject::connect(duck, SIGNAL(clicked()), Rhythm_GameClass, SLOT(check_answer()));
        QObject::connect(apple, SIGNAL(clicked()), Rhythm_GameClass, SLOT(check_answer()));
        QObject::connect(left_button_2, SIGNAL(clicked()), Rhythm_GameClass, SLOT(change_before_stage()));
        QObject::connect(right_button_2, SIGNAL(clicked()), Rhythm_GameClass, SLOT(change_next_stage()));
        QObject::connect(stage_4, SIGNAL(clicked()), Rhythm_GameClass, SLOT(play_video()));
        QObject::connect(stage_5, SIGNAL(clicked()), Rhythm_GameClass, SLOT(play_video()));
        QObject::connect(stage_6, SIGNAL(clicked()), Rhythm_GameClass, SLOT(play_video()));
        QObject::connect(return_main_2, SIGNAL(clicked()), Rhythm_GameClass, SLOT(enter_stage()));
        QObject::connect(quit_button_3, SIGNAL(clicked()), Rhythm_GameClass, SLOT(exit_game()));
        QObject::connect(elephant, SIGNAL(clicked()), Rhythm_GameClass, SLOT(check_answer()));
        QObject::connect(frog, SIGNAL(clicked()), Rhythm_GameClass, SLOT(check_answer()));
        QObject::connect(gorilla, SIGNAL(clicked()), Rhythm_GameClass, SLOT(check_answer()));
        QObject::connect(horse, SIGNAL(clicked()), Rhythm_GameClass, SLOT(check_answer()));

        stacked_widget->setCurrentIndex(7);


        QMetaObject::connectSlotsByName(Rhythm_GameClass);
    } // setupUi

    void retranslateUi(QMainWindow *Rhythm_GameClass)
    {
        Rhythm_GameClass->setWindowTitle(QApplication::translate("Rhythm_GameClass", "Rhythm_Game", 0));
        start_button->setText(QString());
        quit_button->setText(QString());
        camera->setText(QString());
        stage_4->setText(QString());
        camera_6->setText(QString());
        stage_5->setText(QString());
        stage_6->setText(QString());
        left_button_2->setText(QString());
        right_button_2->setText(QString());
        camera_7->setText(QString());
        left_button->setText(QString());
        right_button->setText(QString());
        stage_1->setText(QString());
        stage_2->setText(QString());
        stage_3->setText(QString());
        camera_2->setText(QString());
        next_button->setText(QString());
        apple->setText(QString());
        bus->setText(QString());
        cat->setText(QString());
        duck->setText(QString());
        camera_3->setText(QString());
        camera_8->setText(QString());
        elephant->setText(QString());
        frog->setText(QString());
        gorilla->setText(QString());
        horse->setText(QString());
        great->setText(QString());
        return_main->setText(QString());
        quit_button_2->setText(QString());
        camera_4->setText(QString());
        camera_5->setText(QString());
        fail->setText(QString());
        quit_button_3->setText(QString());
        return_main_2->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class Rhythm_GameClass: public Ui_Rhythm_GameClass {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_RHYTHM_GAME_H
